[General]
Program=Creatures
Version=Version 1.0e Single User Copy
Copyright=Copyright (c) 1996 - Future Skill Software
NumDisks=1
InstallBDE=0
InstallSQL=0
ServerDir=c:\creature\
LocalStationDir=c:\
AppName=Creature
PMGroup=Creatures

[SubDirs]
0=samples

[Disk1]
readme.txt=i
creature.exe=i
ctl3dv2.dll=s
startup.ini=i
startup.fld=i
big.fld=0
stable.fld=0
sex.fld=0
fission.fld=0
radio.fld=0


[Disk2]

[PMGroup]
Creature=i
