#!/usr/bin/env node
// Embed the six shipped .FLD files as base64 so the page is fully
// client-side — fetch() of a local file is blocked under file://.
//
//     node build-fields.js
//
// The .FLD files never change, so this is a one-time asset step, not a build.
'use strict';

var fs = require('fs');
var path = require('path');

var SRC = path.join(__dirname, '..', 'original', 'files');
var NAMES = ['STABLE', 'BIG', 'STARTUP', 'SEX', 'FISSION', 'RADIO'];

var out = [
  '// Generated by build-fields.js — do not edit.',
  '// The six field files shipped with Creatures 1.0, base64 encoded.',
  'const FIELDS = {',
];
NAMES.forEach(function (n) {
  var b = fs.readFileSync(path.join(SRC, n + '.FLD'));
  out.push('  ' + n + ': "' + b.toString('base64') + '",');
});
out.push('};');

fs.writeFileSync(path.join(__dirname, 'fields.js'), out.join('\n') + '\n');
console.log('wrote fields.js (' + NAMES.length + ' fields)');
